version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:24.11@sha256:ee64caf152fe572cf67dec4dafeec8e6e345c02e7061909a05e95fb7cbd48d89
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Prepare
          command: pnpm run dev:prepare
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Release
          command: pnpm semantic-release

workflows:
  release:
    jobs:
      - release
