version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:22.17@sha256:e9a3e9f9922042b89a4b954f48f19bee7646266804e7c69c415a4bb269aa4f80
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Prepare
          command: pnpm run dev:prepare
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Release
          command: pnpm semantic-release

workflows:
  release:
    jobs:
      - release
