version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:22.13@sha256:f5dfaaeb91ce8fb246355b197df84c74491f4c426844db24791bd9be114db2a0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Prepare
          command: pnpm run dev:prepare
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Release
          command: pnpm semantic-release

workflows:
  release:
    jobs:
      - release
