version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:20.18@sha256:778e45b58d291463fa9ba25bc15d66a42cc36a57345e0c7e6e1fa73bf6723ab3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Prepare
          command: pnpm run dev:prepare
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Release
          command: pnpm semantic-release

workflows:
  release:
    jobs:
      - release
