version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:22.18@sha256:64ceff316e55ef43f35db465d4c98bff8dc862a7f348ed784b91e7d956d34d38
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Prepare
          command: pnpm run dev:prepare
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Release
          command: pnpm semantic-release

workflows:
  release:
    jobs:
      - release
