version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  release:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Prepare
          command: yarn dev:prepare
      - run: yarn semantic-release

workflows:
  release:
    jobs:
      - release
