version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Prepare
          command: pnpm run dev:prepare
      - run:
          name: Release
          command: pnpm run semantic-release

workflows:
  release:
    jobs:
      - release
