version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  release:
    docker:
      - image: cimg/node:19.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Prepare
          command: yarn dev:prepare
      - run:
          name: Release
          command: yarn semantic-release

workflows:
  release:
    jobs:
      - release
