version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:22.21@sha256:118f55b7a525f31aea3e51fc2028643135256cc6e26e27517df45bde9a2fb1a3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Prepare
          command: pnpm run dev:prepare
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Release
          command: pnpm semantic-release

workflows:
  release:
    jobs:
      - release
