version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:20.18@sha256:c2ea6166daf4ed37d0abdaf9186798e0c73e75a9f1f3858b69bb770755a59cca
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Prepare
          command: pnpm run dev:prepare
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Release
          command: pnpm semantic-release

workflows:
  release:
    jobs:
      - release
